SELECT TOP (1000) [TimesheetID]
      ,[TeamMemberID]
      ,[WorkDate]
      ,[DayOfWeek]
      ,[ProjectID]
      ,[Description]
      ,[IsBillable]
      ,[Comments]
      ,[StartTime]
      ,[EndTime]
      ,[HoursWorked]
  FROM [TimesheetDB].[dbo].[Timesheet]
